# Matrix multiplication

In [1]:
import nbloader
import tensorflow as tf
import numpy as np
from demo_util import gpusession
print ("Packages loaded.")

Importing Jupyter notebook from [demo_util.ipynb]
Packages loaded.


Test multiple matrix multiplications 

In [2]:
# Make graph
tf_A = tf.placeholder("float", [None, 150, 10])
tf_b = tf.placeholder("float", [None, 10, 1])
tf_allMuls = tf.matmul(tf_A, tf_b)
print tf_A
print tf_b
print tf_allMuls

# Set data
nData = 5
A = np.random.rand(nData,150,10)
b = np.random.rand(nData,10,1)
sess = gpusession()
tf_res = sess.run(tf_allMuls,feed_dict={tf_A:A,tf_b:b})

# Matrix multiplication using numpy
np_res = np.zeros((nData,150,1))
for i in range(nData):
    curr_A = np.reshape(A[i,:,:],newshape=(150,10))
    curr_b = np.reshape(b[i,:,:],newshape=(10,1)) 
    np_res[i,:] = np.matmul(curr_A,curr_b)

# Check results
for i in range(nData):
    err = tf_res[i,:,:].squeeze()-np_res[i,:,:].squeeze()
    err_norm = np.linalg.norm(err)
    print ("[%d] Err:%.4e"%(i,err_norm))

Tensor("Placeholder:0", shape=(?, 150, 10), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 10, 1), dtype=float32)
Tensor("MatMul:0", shape=(?, 150, 1), dtype=float32)
[0] Err:1.8863e-06
[1] Err:1.8052e-06
[2] Err:1.4090e-06
[3] Err:1.4230e-06
[4] Err:2.1831e-06


Test reshape

In [20]:
# Make graph
tf_a = tf.placeholder("float", [None,6])
tf_a_rsh = tf.reshape(tf_a,shape=[-1,3,2])
# Generate data
nData = 10
np_a = np.random.rand(nData,6)
sess = gpusession()
np_a_rsh = sess.run(tf_a_rsh,feed_dict={tf_a:np_a})
# Check data
for i in range(nData):
    curr_a = np_a[i,:]
    print ('\n[%02d/%d]'%(i+1,nData))
    print (' curr_a:\n%s' % (curr_a))
    print (' curr_a_rsh:\n%s' % (np.reshape(curr_a,[3,2])))
    print (' tf_a_rsh:\n%s' % (np_a_rsh[i,:,:]))
    print ("  'curr_a_rsh' and 'tf_a_rsh' should be the same.")


[01/10]
 curr_a:
[0.65396345 0.52695408 0.80762737 0.16353129 0.10547146 0.83903114]
 curr_a_rsh:
[[0.65396345 0.52695408]
 [0.80762737 0.16353129]
 [0.10547146 0.83903114]]
 tf_a_rsh:
[[0.65396345 0.52695405]
 [0.8076274  0.16353129]
 [0.10547145 0.83903116]]
  'curr_a_rsh' and 'tf_a_rsh' should be the same.

[02/10]
 curr_a:
[0.27385714 0.72636872 0.2105374  0.68067634 0.92318967 0.67967588]
 curr_a_rsh:
[[0.27385714 0.72636872]
 [0.2105374  0.68067634]
 [0.92318967 0.67967588]]
 tf_a_rsh:
[[0.27385715 0.7263687 ]
 [0.2105374  0.68067634]
 [0.9231897  0.6796759 ]]
  'curr_a_rsh' and 'tf_a_rsh' should be the same.

[03/10]
 curr_a:
[0.35259091 0.15526107 0.56665441 0.96776311 0.03615346 0.81053072]
 curr_a_rsh:
[[0.35259091 0.15526107]
 [0.56665441 0.96776311]
 [0.03615346 0.81053072]]
 tf_a_rsh:
[[0.35259092 0.15526107]
 [0.5666544  0.9677631 ]
 [0.03615345 0.8105307 ]]
  'curr_a_rsh' and 'tf_a_rsh' should be the same.

[04/10]
 curr_a:
[0.75884189 0.26300952 0.72216289 0.87765113 0